name: Deploy Worker
on:
  push:
    branches:
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Deploy Preview
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --env preview