name: Deploy Worker
on:
  push:
    branches:
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Deploy Preview
    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy to Preview
        run: wrangler deploy --env preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}