name: Deploy Worker
on:
  push:
    branches:
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Deploy Preview
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build with OpenNext
        run: npx open-next build

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy to Preview
        run: wrangler deploy --env preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}